### PR TITLE
poplar_recovery_builder.sh: Enable partial builds

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by alexelder** [comment]
This is great!  I've had it on my to-do list for a long time, and I like how you did it.
I scanned it and it all looks very good to me.  My one comment is that maybe "rootfs"
should be "filesystems" or "data" or something, because it's really saving everything
that's data on the target, not just the root file system.

I'll leave it to Shawn to pull this when he's ready.

**Comment by vchong** [comment]
@alexelder Thanks! The weird thing about this is `poplar_recovery_builder.sh rootfs.tar.gz {layout,loader,boot}` looks weird, so I reversed the args position in https://github.com/Linaro/poplar-tools/pull/13 and make the rootfs tar file arg conditionally optional. Can you please see if that's better? In it I also used `system` (same as hikey*) instead of `rootfs`. If this is preferred then I can also change this one to use `system` instead.

**Comment by vchong** [comment]
@alexelder Also, boot partition dependency on loader is due to https://github.com/Linaro/poplar-tools/blob/latest/poplar_recovery_builder.sh#L584. What is this copy for?

**Comment by alexelder** [comment]
On 10/29/2017 10:43 AM, vchong wrote:
> @alexelder <https://github.com/alexelder> Thanks! The weird thing about this is |poplar_recovery_builder.sh rootfs.tar.gz {layout,loader,boot}| looks weird, so I reversed the args position in #13 <https://github.com/Linaro/poplar-tools/pull/13> and make the rootfs tar file arg conditionally optional. Can you please see if that's better? In it I also used |system| (same as hikey*) instead of |rootfs|. If this is preferred then I can also change this one to use |system| instead.

I suck at Gerrit and GitHub so I'm just going to respond by e-mail.

I agree that reordering the arguments is better--put the optional file system
image argument at the end.  And I think "system" to mean "whatever file systems
get installed" (which covers the Android case better) is better than "rootfs".

					-Alex

**Comment by alexelder** [comment]
On 10/29/2017 10:54 AM, vchong wrote:
> @alexelder <https://github.com/alexelder> Also, boot partition dependency on loader is due to https://github.com/Linaro/poplar-tools/blob/latest/poplar_recovery_builder.sh#L584. What is this copy for?

The copy can go away.  I put it there as a way to have the current
"loader.bin" image that's sitting in partition 1 be resident in a
file.  But it doesn't really help anything--you can always get the
*real* one from the partition anyway.  So you can feel free to remove
that copy and eliminate that dependency as far as I'm concerned.

You're not the first person who's asked about that...

					-Alex

**Comment by vchong** [comment]
Email response is fine. :)
Thanks! I've removed the dependency on #13.
Closing this as replaced by #13.

**Pull request closed without merging**
