### PR TITLE
build_instructions.md: Add notes for possible mkimage error

### PR DESCRIPTION
**Pull request by vchong**
and link to resolution.

Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by shawnguo2** [comment]
Hi Victor, I created a patch "generate_mbr.sh: let it cope with old version sfdisk" fix the sfdisk problem.  Would you mind changing your patch to drop sfdisk part.  Asking users to build sfdisk from source is not so friendly, IMHO.  Thanks, Shawn.

**Comment by vchong** [comment]
@shawnguo2 sfdisk part dropped. Where's the patch for generate_mbr.sh btw? Thanks!

**Comment by shawnguo2** [comment]
@vchong Thanks for the change. I sent the generate_mbr.sh patch to project-aspen-dev list with you on copy last night.

**Comment by vchong** [comment]
Oh ok. I see it now. Thought it was on github. Thanks!

**Pull request merged**
