### PR TITLE
build_instructions.md: Add notes to build and test OP-TEE

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by shawnguo2** [comment]
I'm booting a OP-TEE enabled kernel with ATF without OP-TEE, and seeing following kernel warnings.  Is it expected?

[    2.457573] sysfs: cannot create duplicate filename '/devices/virtual/misc/ion'
[    2.464913] ------------[ cut here ]------------
[    2.469537] WARNING: CPU: 0 PID: 1 at fs/sysfs/dir.c:31 sysfs_warn_dup+0x5c/0x78
[    2.476933] Modules linked in:
[    2.479986] 
[    2.480100] usb 5-1: new high-speed USB device number 2 using xhci-hcd
[    2.487997] CPU: 0 PID: 1 Comm: swapper/0 Not tainted 4.9.51-03844-g49d1ed4d94d8 #82
[    2.495741] Hardware name: HiSilicon Poplar Development Board (DT)
[    2.501917] task: ffff800078878000 task.stack: ffff800078834000
[    2.507834] PC is at sysfs_warn_dup+0x5c/0x78
[    2.512187] LR is at sysfs_warn_dup+0x5c/0x78
[    2.516540] pc : [<ffff000008231fcc>] lr : [<ffff000008231fcc>] pstate: 60000045
[    2.523935] sp : ffff800078837a70
[    2.527245] x29: ffff800078837a70 x28: 0000000000000000 
[    2.532558] x27: ffff8000782ba410 x26: 0000000000a0003a 
[    2.537871] x25: 0000000000000000 x24: 0000000000000000 
[    2.543184] x23: ffff800078993f80 x22: 0000000000000000 
[    2.548498] x21: ffff800078994e88 x20: ffff000008b99e78 
[    2.553811] x19: ffff800078816000 x18: 0000000000000010 
[    2.559124] x17: 0000000000000001 x16: 0000000000000019 
[    2.564437] x15: 0000000000000006 x14: ffff000088d55aa7 
[    2.569750] x13: ffff000008d55ab5 x12: 0000000000000007 
[    2.575063] x11: ffff8000788377d0 x10: 0000000005f5e0ff 
[    2.580375] x9 : 0000000000000103 x8 : 696d2f6c61757472 
[    2.585689] x7 : 69762f7365636976 x6 : ffff000008d55afa 
[    2.591001] x5 : ffff00000852f9e0 x4 : 0000000000000000 
[    2.596314] x3 : 0000000000000000 x2 : ffff000008ccac30 
[    2.601627] x1 : ffff800078834000 x0 : 0000000000000043 
[    2.606940] 
[    2.608428] ---[ end trace fb2789af8a7908ca ]---
[    2.613040] Call trace:
[    2.615483] Exception stack(0xffff8000788378a0 to 0xffff8000788379d0)
[    2.621922] 78a0: ffff800078816000 0001000000000000 ffff800078837a70 ffff000008231fcc
[    2.629754] 78c0: 0000000000000043 0000000000000006 ffff8000788378f0 ffff0000080e1cac
[    2.637585] 78e0: ffff000008ade5a8 0000000108ccac18 ffff800078837990 ffff0000080e1f74
[    2.645416] 7900: ffff800078816000 ffff000008b99e78 ffff800078994e88 0000000000000000
[    2.653248] 7920: ffff800078993f80 0000000000000000 0000000000000000 0000000000a0003a
[    2.661080] 7940: 0000000000000043 ffff800078834000 ffff000008ccac30 0000000000000000
[    2.668911] 7960: 0000000000000000 ffff00000852f9e0 ffff000008d55afa 69762f7365636976
[    2.676743] 7980: 696d2f6c61757472 0000000000000103 0000000005f5e0ff ffff8000788377d0
[    2.684574] 79a0: 0000000000000007 ffff000008d55ab5 ffff000088d55aa7 0000000000000006
[    2.692405] 79c0: 0000000000000019 0000000000000001
[    2.697279] [<ffff000008231fcc>] sysfs_warn_dup+0x5c/0x78
[    2.702675] [<ffff0000082320fc>] sysfs_create_dir_ns+0x9c/0xb0
[    2.708509] [<ffff00000834555c>] kobject_add_internal+0x94/0x290
[    2.714513] [<ffff0000083457e0>] kobject_add+0x88/0xd8
[    2.719651] [<ffff0000085d3094>] device_add+0xcc/0x598
[    2.724787] [<ffff0000085d37a0>] device_create_groups_vargs+0x108/0x118
[    2.731399] [<ffff0000085d3880>] device_create_with_groups+0x40/0x48
[    2.737752] [<ffff0000085c4e98>] misc_register+0x180/0x1c0
[    2.743237] [<ffff0000087a3478>] ion_device_create+0x58/0x180
[    2.748982] [<ffff000008c56434>] ion_dummy_init+0x1c/0x204
[    2.754467] [<ffff0000080830b8>] do_one_initcall+0x38/0x128
[    2.760039] [<ffff000008c20ce8>] kernel_init_freeable+0x1a4/0x240
[    2.766133] [<ffff0000088cd158>] kernel_init+0x10/0x100
[    2.771355] [<ffff000008082e80>] ret_from_fork+0x10/0x50
[    2.776709] kobject_add_internal failed for ion with -EEXIST, don't try to register things with the same name in the same directory.
[    2.788672] ------------[ cut here ]------------
[    2.793290] WARNING: CPU: 0 PID: 1 at lib/kobject.c:240 kobject_add_internal+0x210/0x290
[    2.801381] Modules linked in:
[    2.804432] 
[    2.805919] CPU: 0 PID: 1 Comm: swapper/0 Tainted: G        W       4.9.51-03844-g49d1ed4d94d8 #82
[    2.814878] Hardware name: HiSilicon Poplar Development Board (DT)
[    2.821054] task: ffff800078878000 task.stack: ffff800078834000
[    2.826971] PC is at kobject_add_internal+0x210/0x290
[    2.832020] LR is at kobject_add_internal+0x210/0x290
[    2.837067] pc : [<ffff0000083456d8>] lr : [<ffff0000083456d8>] pstate: 60000045
[    2.844462] sp : ffff800078837ad0
[    2.847771] x29: ffff800078837ad0 x28: 0000000000000000 
[    2.853085] x27: ffff8000782ba410 x26: 0000000000a0003a 
[    2.858398] x25: 0000000000000000 x24: 0000000000000000 
[    2.863711] x23: ffff800078993f80 x22: 00000000ffffffef 
[    2.869023] x21: ffff800078993f80 x20: 0000000000000000 
[    2.874337] x19: ffff8000782ba410 x18: 0000000000000010 
[    2.879649] x17: 0000000000000001 x16: 0000000000000019 
[    2.884962] x15: 0000000000000006 x14: 72206f7420797274 
[    2.890275] x13: 2074276e6f64202c x12: 5453495845452d20 
[    2.895588] x11: 68746977206e6f69 x10: 20726f662064656c 
[    2.900902] x9 : 000000000000013b x8 : 696420656d617320 
[    2.906215] x7 : 656874206e692065 x6 : ffff000008d55b2f 
[    2.911529] x5 : ffff00000852f9e0 x4 : 0000000000000000 
[    2.916842] x3 : 0000000000000000 x2 : ffff000008ccac30 
[    2.922155] x1 : ffff800078834000 x0 : 0000000000000078 
[    2.927467] 
[    2.928952] ---[ end trace fb2789af8a7908cb ]---
[    2.933564] Call trace:
[    2.936007] Exception stack(0xffff800078837900 to 0xffff800078837a30)
[    2.942444] 7900: ffff8000782ba410 0001000000000000 ffff800078837ad0 ffff0000083456d8
[    2.950276] 7920: 0000000000000078 0000000000000002 ffff800078837950 ffff0000080e1cac
[    2.958107] 7940: ffff000008ade5a8 0000000108ccac18 ffff8000788379f0 ffff0000080e1f74
[    2.965939] 7960: ffff8000782ba410 0000000000000000 ffff800078993f80 00000000ffffffef
[    2.973770] 7980: ffff800078993f80 0000000000000000 0000000000000000 0000000000a0003a
[    2.981602] 79a0: 0000000000000078 ffff800078834000 ffff000008ccac30 0000000000000000
[    2.989433] 79c0: 0000000000000000 ffff00000852f9e0 ffff000008d55b2f 656874206e692065
[    2.997265] 79e0: 696420656d617320 000000000000013b 20726f662064656c 68746977206e6f69
[    3.005096] 7a00: 5453495845452d20 2074276e6f64202c 72206f7420797274 0000000000000006
[    3.012927] 7a20: 0000000000000019 0000000000000001
[    3.017802] [<ffff0000083456d8>] kobject_add_internal+0x210/0x290
[    3.023893] [<ffff0000083457e0>] kobject_add+0x88/0xd8
[    3.029028] [<ffff0000085d3094>] device_add+0xcc/0x598
[    3.034164] [<ffff0000085d37a0>] device_create_groups_vargs+0x108/0x118
[    3.040776] [<ffff0000085d3880>] device_create_with_groups+0x40/0x48
[    3.047128] [<ffff0000085c4e98>] misc_register+0x180/0x1c0
[    3.052612] [<ffff0000087a3478>] ion_device_create+0x58/0x180
[    3.058355] [<ffff000008c56434>] ion_dummy_init+0x1c/0x204
[    3.063838] [<ffff0000080830b8>] do_one_initcall+0x38/0x128
[    3.069410] [<ffff000008c20ce8>] kernel_init_freeable+0x1a4/0x240
[    3.075502] [<ffff0000088cd158>] kernel_init+0x10/0x100
[    3.080723] [<ffff000008082e80>] ret_from_fork+0x10/0x50
[    3.086098] ion: failed to register misc device.
[    3.090895] optee: probing for conduit method from DT.
[    3.096053] optee: api uid mismatch

**Comment by vchong** [comment]
> [ 2.457573] sysfs: cannot create duplicate filename '/devices/virtual/misc/ion'

@shawnguo2 looks like you're right. Both Hisi and SWG ION patches cannot coexist so I'll remove the SWG ION patches from 4.9 kernel PR (https://github.com/Linaro/poplar-linux/pull/2).

**Comment by vchong** [comment]
The optee_os port by itself isn't that complicated to the point where we need to maintain a separate fork. optee_os PRs also move pretty fast usually, and patches for adding extra board/platform support can be merged in just a few days, so another fork is just extra maintenance we don't really need. It's also better to work directly upstream since that that means we will automatically be in sync with optee_client and optee_test repos.

**Comment by shawnguo2** [comment]
In that case, we should probably get poplar support into optee_os upstream first, and then merge the document update in this PR.

**Comment by vchong** [comment]
Ok, agree. Let's hope the internal patch review clears asap so we can send the patch upstream.

**Pull request merged**
