### PR TITLE
poplar_recovery_builder.sh: Add loader+boot builds

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
Also increase loglevel to 8

**Comment by shawnguo2** [comment]
@vchong I prefer to drop loglevel completely.  What do you think?

**Comment by vchong** [comment]
> I prefer to drop loglevel completely. What do you think?

@shawnguo2 It's up to you since you're the maintainer! ; ) I just thought that people who use this tool are most probably going to be doing development and so would usually want or prefer more logs than less. Lemme know what you decide and I'll change accordingly. Thanks!

**Comment by shawnguo2** [comment]
> Lemme know what you decide and I'll change accordingly.

Let's drop loglevel.

**Comment by vchong** [comment]
loglevel dropped and commit message updated.

**Pull request merged**
